version: '3.8'

services:
  socket-sensores:
    image: socketsensores
    ports:
      - "1544:1544"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - my_network

  Datos_Sensores:
    image: datossensores
    ports:
      - "1534:1534"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3305
      - MYSQL_DATABASE=DatosSensores
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - my_network

  mysql:
    image: mysql:latest
    ports:
      - "3305:3305"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=DatosSensores
    networks:
      - my_network

networks:
  my_network:
