version: '3.8'

services:
  socket-sensores:
    build:
      context: ./socketsensores
    ports:
      - "1544:1544"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - my_network

  datos_sensores:
    build:
      context: ./datos_sensores
    ports:
      - "1534:1534"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3305
      - MYSQL_DATABASE=datossensores
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - my_network
      
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3305
      - MYSQL_DATABASE_DATOSSENSORES=datossensores
      - MYSQL_DATABASE_INVERNADERO=invernadero
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - my_network
      
  detector:
    build:
      context: ./detector
    ports:
      - "1333:1333"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3305
      - MYSQL_DATABASE_DATOSSENSORES=datossensores
      - MYSQL_DATABASE_INVERNADERO=invernadero
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - my_network  

  sistemamensajeria:
    build:
      context: ./sistemamensajeria
    ports:
      - "1322:1322"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - my_network  

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - my_network

  mysql:
    image: mysql:latest
    ports:
      - "3305:3305"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - my_network
    volumes:
      - ./mysql-initdb:/docker-entrypoint-initdb.d

networks:
  my_network:
